stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - echo "Running build job..."
    - docker-compose build

deploy-job:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - docker-compose down
    - docker-compose up -d