stages:
  - test
  - deploy

test-job:
  stage: test
  only:
    refs:
      - main
  tags:
    - main
  script:
    - docker-compose down
    - git pull https://$GITLAB_USER:$GITLAB_PASS@gitlab.cs.taltech.ee/alpari/loputoo-2024.git
    - docker compose -f webapp/test/docker-compose.yml down
    - docker compose -f webapp/test/docker-compose.yml build msi-adrift-project
    - docker compose -f webapp/test/docker-compose.yml up --abort-on-container-exit

deploy-job:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - docker-compose down
    - git pull https://$GITLAB_USER:$GITLAB_PASS@gitlab.cs.taltech.ee/alpari/loputoo-2024.git
    - docker-compose up -d