version: "3"
services:
  msi-adrift:
    build: .
    volumes:
      - output_volume:/output
    ports:
      - "5000:5000"
#    command: ["pytest", "--cov=.", "--cov-report=term-missing", "test_app_unittest.py"]

volumes:
  output_volume:
